### ISSUE TITLE
recommended approach for import and integration

### ISSUE THREAD

**Issue by kmacpher67** [goeh/grails-crm-core#4]
What's the recommended approach for importing data and integration? 
- I know that's a loaded question, simple to ask yet impossibly long to answer. 

Two different questions here: 
1> simple initial provisioning 
vs
2> EAI - app integration maybe using EIP but then that gets ugly and uber complicated. or simple point-to-point integration. 

What are you thoughts or experiences on approaches? 
Is there something already built into the service layer for this?

**Comment by goeh** [comment]
There is no specific features built in for data importing or integration. However, the standard GR8 CRM service methods list..., create... and update... works well in integration scenarios. Personally I have only experience with reading Microsoft Excel files using Apache POI and inserting/updating data using the standard GR8 CRM service methods. I once tried to develop a generic crm-import plugin with ETL features, but (due to lack of time) I ended up doing a project specific import.

**Comment by kmacpher67** [comment]
I found a sample somewhere using BootStrap.groovy
use the service layer seems to be the best method: 

```
def BMW = crmContactService.createCompany(name: "BMW", true)
def contact = crmContactService.createPerson(related: [BMW, company], firstName: firstName, lastName: lastName, telephone: "08-${System.currentTimeMillis().toString().substring(6)}", true)
```

yeah, wasn't sure if you had a plugin-feature or service layer that could be passed a handle or something. I suspect the doc for that is just looking at the Service layer class.
