### ISSUE TITLE
Grails 3.x version

### ISSUE THREAD

**Issue by rgoldberg** [goeh/grails-crm-core#5]
Are there versions of the CRM plugins for use with Grails 3.x?

If not, will you ever provide Grails 3.x versions?

Thanks.

**Comment by goeh** [comment]
There will definitely be Grails 3.x versions of GR8 CRM features! However we will use the opportunity to change most of them so they can be used both as a plugin in a monolith application and as a separate isolated (micro)service. I will personally allocate time in Januari 2016 to accelerate the migration. I have done some initial prototyping with the crm-content plugin and the work will be public in a few weeks.

**Comment by rgoldberg** [comment]
Any update on when Grails 3 versions will be available?

Thanks.

**Comment by goeh** [comment]
I've spent a lot of time thinking about the direction for next major version of GR8 CRM. This will be the third iteration of the plugins and I want to do it right this time. I want each plugin to support two modes of operation:
1. as a plugin in a monolith application (like GR8 CRM 2.x)
2. as a stand alone micro service with a standard way of communicating with other GR8 CRM services

To reach a broader audience I first planned to base the new plugins on plain Spring Boot. I have developed a lot of micro services with Spring Boot and Spring Cloud the last 8 months and I really like it. But the more I prototype GR8 CRM with Spring Boot and Grails 3.x I really love the extra features that Grails gives me. Like the plugin architecture, GORM, gsp, profiles, etc.

So as you can see I haven't yet started the development of next major version of GR8 CRM yet, which means it's far away from release. Sad but true. I wish I had some funding because I have lots of ideas but no time to implement them.

**Comment by muser83** [comment]
Any good news or updates about the project?

**Comment by goeh** [comment]
Unfortunately I'm too busy with GR8 CRM 2.x work right now so I don't have time over for 3.x. I'm so frustrated by this situation! I'm working day and night.
I've done some prototyping. I'm thinking about doing a combination of Spring Boot Starters and Grails 3.2+ plugins. Spring Boot starter jars for services and GORM 6 for persistence. Then Grails 3.2+ plugins for REST APIs and GSP UI (if I continue that route).
I don't have any repositories to share at the moment, it's just random prototypes. But as soon as I have something to share I will upload to https://github.com/gr8crm
Thanks for your interest in GR8 CRM. If you have any suggestions on how to move this project forward please share.
